import React, { createContext, useContext, useState, useEffect, useCallback, useMemo, ReactNode } from 'react';

export type Language = 'en' | 'fr' | 'ar';

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: string, params?: Record<string, any>) => string;
  dir: 'ltr' | 'rtl';
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Nav
    'nav.services': 'Services',
    'nav.howItWorks': 'How It Works',
    'nav.offers': 'Offers',
    'nav.technology': 'Technology',
    'nav.contact': 'Contact',
    'nav.faq': 'FAQ',
    'nav.simulator': 'Simulator',
    // Hero
    'hero.headline': 'DOMOSIA, Your property, our expertise.',
    'hero.subtext': 'Turn your property into effortless, steady income with expert management and smart automation.',
    'hero.cta1': 'Get Started',
    'hero.cta2': 'Learn More',
    // Services
    'services.title': 'What We Do',
    'services.subtitle': 'Comprehensive property management tailored to maximize your returns',
    'services.fullMgmt.title': 'Full Management',
    'services.fullMgmt.desc': 'Guest communication, cleaning coordination, dynamic pricing, and maintenance — all handled seamlessly.',
    'services.marketing.title': 'Marketing & Booking',
    'services.marketing.desc': 'Professional listing setup, multi-platform visibility, and dynamic pricing to maximize occupancy.',
    'services.reporting.title': 'Owner Reporting',
    'services.reporting.desc': 'Monthly dashboards with income, occupancy rates, and maintenance details at your fingertips.',
    // How It Works
    'how.title': 'How It Works',
    'how.subtitle': 'From onboarding to continuous management, we make it seamless',
    'how.step1.title': 'Prep Week',
    'how.step1.desc': 'Installation of connected door handles, cleaning, and equipment audit.',
    'how.step2.title': 'Going Live',
    'how.step2.desc': 'Professional photoshoot, optimized listings, and launch across all major platforms.',
    'how.step3.title': 'Continuous Management',
    'how.step3.desc': 'DOMOSIA handles everything — bookings, guest communication, cleaning, maintenance, and full operational oversight.',
    'how.digitalNote': 'Digital-Only Management is available for landlords who prefer to handle on-site operations themselves but want professional support with listings, pricing, and reservations.',
    'how.learnMore': 'Learn More',
    // Offers
    'offers.title': 'Our Offers',
    'offers.subtitle': 'Choose the plan that fits your needs',
    'offers.full.title': 'Full Management',
    'offers.full.badge': 'Premium Service',
    'offers.full.desc': 'Complete hands-off property management. Dynamic pricing, guest communication, cleaning, maintenance, and live dashboards.',
    'offers.full.f1': 'End-to-end guest management',
    'offers.full.f2': 'Professional cleaning coordination',
    'offers.full.f3': 'Dynamic pricing optimization',
    'offers.full.f4': 'Maintenance & inspections',
    'offers.full.f5': 'Real-time owner dashboard',
    'offers.full.cta': 'Book Consultation',
    'offers.digital.title': 'Digital-Only',
    'offers.digital.badge': 'Optional Support',
    'offers.digital.desc': 'Listing optimization, AI-driven pricing, and reservation support for landlords handling on-ground operations.',
    'offers.digital.f1': 'Multi-platform listing setup',
    'offers.digital.f2': 'AI-driven dynamic pricing',
    'offers.digital.f3': 'Reservation management',
    'offers.digital.f4': 'Performance analytics',
    'offers.digital.cta': 'Learn More',
    // Technology
    'tech.title': 'Smart Technology',
    'tech.subtitle': 'Powered by innovation for maximum efficiency',
    'tech.smartAccess.title': 'Smart Access',
    'tech.smartAccess.desc': 'Keyless check-in and check-out for seamless guest experiences.',
    'tech.automation.title': 'Automation System',
    'tech.automation.desc': 'Centralized booking, cleaning, and guest management.',
    'tech.dashboard.title': 'Owner Dashboard',
    'tech.dashboard.desc': 'Live revenue, occupancy, and reviews at a glance.',
    'tech.pricing.title': 'Dynamic Pricing',
    'tech.pricing.desc': 'AI-driven optimization for maximum revenue.',
    'tech.payments.title': 'Secure Payments',
    'tech.payments.desc': 'Safe and transparent transactions.',
    'tech.platforms.title': 'Integrated Platforms',
    'tech.platforms.desc': 'Sync with Airbnb, Booking.com, and more.',
    // CTA
    'cta.title': 'Ready to Maximize Your Property\'s Potential?',
    'cta.subtitle': 'Let DOMOSIA transform your property into a premium income source.',
    'cta.audit': 'Request Revenue Simulation for Free',
    'cta.consultation': 'Schedule a Consultation',
    // Footer
    'footer.tagline': 'Your property, our expertise.',
    'footer.quickLinks': 'Quick Links',
    'footer.contact': 'Contact',
    'footer.followUs': 'Follow Us',
    'footer.rights': '© 2026 DOMOSIA. All rights reserved.',
    // Floating
    'float.whatsapp': 'Chat on WhatsApp',
    'float.email': 'Send Email',

    // Simulator Translations
    "common.next": "Next",
    "common.back": "Back",
    "common.mad": "MAD",
    "common.madPerYear": "MAD/year",
    "common.madPerNight": "MAD/night",
    "common.madPerMonth": "MAD/month",
    "steps.contact": "Contact",
    "steps.property": "Property",
    "steps.location": "Location",
    "steps.amenities": "Amenities",
    "contact.intro": "Please enter your details to receive your personalized simulation.",
    "contact.fullName": "Full name",
    "contact.fullNamePlaceholder": "Ex: Ahmed Benali",
    "contact.fullNameError": "Please enter your full name (min. 3 characters)",
    "contact.email": "Email",
    "contact.emailPlaceholder": "Ex: ahmed@email.com",
    "contact.emailError": "Please enter a valid email address",
    "contact.phone": "Phone",
    "contact.phonePlaceholder": "Ex: +212 6 12 34 56 78",
    "contact.phoneError": "Valid Moroccan number required (ex: +212612345678 or 0612345678)",
    "property.type": "Property type",
    "property.studio": "Studio",
    "property.apartment": "Apartment",
    "property.villa": "Villa",
    "property.riad": "Riad",
    "property.bedrooms": "Bedrooms",
    "property.beds": "Beds",
    "property.bathrooms": "Bathrooms",
    "property.toilets": "Toilets",
    "location.city": "City",
    "location.cityPlaceholder": "Select a city",
    "location.neighborhood": "Neighborhood",
    "location.neighborhoodPlaceholder": "Select a neighborhood",
    "location.longTermRent": "Long-term rent",
    "location.longTermRentHint": "Used to compare with short-term rental revenue",
    "location.outOfRange": "Data out of range",
    "location.fixValues": "Please fix the values before continuing.",
    "amenities.quality": "Furniture quality",
    "amenities.basic": "Basic",
    "amenities.standard": "Standard",
    "amenities.luxury": "Luxury",
    "amenities.label": "Amenities",
    "amenities.wifi": "WiFi",
    "amenities.ac": "Air conditioning",
    "amenities.pool": "Pool",
    "amenities.parking": "Parking",
    "amenities.terrace": "Terrace",
    "amenities.kitchen": "Equipped kitchen",
    "amenities.washer": "Washing machine",
    "amenities.tv": "TV",
    "amenities.garden": "Garden",
    "amenities.seaView": "Sea view",
    "amenities.fireplace": "Fireplace",
    "amenities.jacuzzi": "Jacuzzi",
    "amenities.gym": "Gym",
    "city.marrakech": "Marrakech",
    "city.casablanca": "Casablanca",
    "city.tangier": "Tangier",
    "city.agadir": "Agadir",
    "city.fes": "Fez",
    "city.essaouira": "Essaouira",
    "city.rabat": "Rabat",
    "city.chefchaouen": "Chefchaouen",
    "neighborhood.Médina": "Medina",
    "neighborhood.Guéliz": "Gueliz",
    "neighborhood.Hivernage": "Hivernage",
    "neighborhood.Palmeraie": "Palmeraie",
    "neighborhood.Targa": "Targa",
    "neighborhood.Route de l'Ourika": "Ourika Road",
    "neighborhood.Maarif": "Maarif",
    "neighborhood.Anfa": "Anfa",
    "neighborhood.Gauthier": "Gauthier",
    "neighborhood.Bourgogne": "Bourgogne",
    "neighborhood.Ain Diab": "Ain Diab",
    "neighborhood.Centre Ville": "City Center",
    "neighborhood.Kasbah": "Kasbah",
    "neighborhood.Ville Nouvelle": "New City",
    "neighborhood.Malabata": "Malabata",
    "neighborhood.Tanja Marina": "Tanja Marina",
    "neighborhood.Cap Spartel": "Cap Spartel",
    "neighborhood.Boukhalef": "Boukhalef",
    "neighborhood.Bord de Mer": "Seaside",
    "neighborhood.Founty": "Founty",
    "neighborhood.Sonaba": "Sonaba",
    "neighborhood.Charaf": "Charaf",
    "neighborhood.Talborjt": "Talborjt",
    "neighborhood.Bay d'Agadir": "Agadir Bay",
    "neighborhood.Fès el-Bali": "Fes el-Bali",
    "neighborhood.Fès el-Jdid": "Fes el-Jdid",
    "neighborhood.Route de Sefrou": "Sefrou Road",
    "neighborhood.Ain Chkef": "Ain Chkef",
    "neighborhood.Diabat": "Diabat",
    "neighborhood.Quartier des Dunes": "Dunes District",
    "neighborhood.Agdal": "Agdal",
    "neighborhood.Hassan": "Hassan",
    "neighborhood.Les Orangers": "Les Orangers",
    "neighborhood.Hay Riad": "Hay Riad",
    "neighborhood.Souissi": "Souissi",
    "neighborhood.Ras el-Maa": "Ras el-Maa",
    "neighborhood.Quartier Andalou": "Andalusian District",
    "month.1": "Jan",
    "month.2": "Feb",
    "month.3": "Mar",
    "month.4": "Apr",
    "month.5": "May",
    "month.6": "Jun",
    "month.7": "Jul",
    "month.8": "Aug",
    "month.9": "Sep",
    "month.10": "Oct",
    "month.11": "Nov",
    "month.12": "Dec",
    "val.maxBedrooms": "Maximum {count} bedrooms for a {type}",
    "val.maxBeds": "Maximum {count} beds for a {type}",
    "val.maxBathrooms": "Maximum {count} bathrooms for a {type}",
    "val.rentRange": "Expected rent between {min} and {max} MAD for {city}",
    "val.rateCap": "The estimated rate exceeds the realistic cap of {cap} MAD/night for this type of property in this city",
    "val.unrealisticRevenue": "The revenue increase seems unrealistic. Please check your data.",
    "form.simulate": "Simulate revenue",
    "results.annualRevenue": "MAD/year",
    "results.simulationFor": "Simulation for",
    "results.vsLongTerm": "vs long-term",
    "results.highSeason": "High season rate",
    "results.lowSeason": "Low season rate",
    "results.occupancy": "Occupancy rate",
    "results.highLow": "high / low",
    "results.longTermRevenue": "Long-term revenue",
    "results.monthlyEstimated": "Estimated monthly revenue",
    "results.formula": "Formula: Revenue = rate/night × occupancy rate × 30 days, with seasonal weighting",
    "results.scenario": "Scenario",
    "results.monthly": "Monthly",
    "results.annual": "Annual",
    "results.highSeasonLabel": "High season",
    "results.lowSeasonLabel": "Low season",
    "results.annualEstimate": "Annual estimate",
    "results.monthlyComparison": "Monthly comparison",
    "results.shortTerm": "Short-term",
    "results.longTerm": "Long-term",
    "results.bestCase": "Best case",
    "results.bestCaseDesc": "Optimal occupancy + high demand",
    "results.worstCase": "Worst case",
    "results.worstCaseDesc": "Low occupancy + extended low season",
    "results.assumptions": "Simulation assumptions",
    "results.newSimulation": "New simulation",
    "results.downloadPdf": "Download PDF",
    "results.generating": "Generating...",
    "results.unrealisticWarning": "Warning: potentially unrealistic results",
    "results.adjustRecommendation": "We recommend relaunching the simulation with adjusted data.",
    "disclaimer": "⚠️ Disclaimer: Estimated results are not guaranteed and may vary depending on local conditions, seasonality, competition, and management quality. This simulation is provided for informational purposes only and does not constitute a contractual commitment from DOMOSIA.",
    "hero.badge": "Rental revenue simulator",
    "hero.title": "Estimate your property's potential in Morocco",
    "hero.subtitle": "Compare short-term vs long-term rental revenue using Moroccan market data.",
    "hero.footer": "Estimates are based on Moroccan market averages and do not constitute financial advice.",
    "assumptions.occupancy": "Occupancy rate:",
    "assumptions.highSeason": "in high season,",
    "assumptions.lowSeason": "in low season",
    "assumptions.seasonInfo": "Morocco high season: summer, spring, December, January + school holidays (varies by city)",
    "assumptions.formulaDetail": "Formula: Revenue = rate/night × occupancy rate × 30 days",
    "assumptions.marketBased": "Rates based on Moroccan market averages for similar properties",
    "assumptions.feesNotIncluded": "Management, cleaning fees and platform commissions are not included",
    "assumptions.scenarios": "Best case: +15% on base estimate. Worst case: -30%",
  },
  fr: {
    'nav.services': 'Services',
    'nav.howItWorks': 'Comment ça marche',
    'nav.offers': 'Offres',
    'nav.technology': 'Technologie',
    'nav.contact': 'Contact',
    'nav.faq': 'FAQ',
    'nav.simulator': 'Simulateur',
    'hero.headline': 'DOMOSIA, Votre bien, notre expertise.',
    'hero.subtext': 'Transformez votre propriété en revenus stables et sans effort grâce à une gestion experte et une automatisation intelligente.',
    'hero.cta1': 'Commencer',
    'hero.cta2': 'En savoir plus',
    'services.title': 'Nos Services',
    'services.subtitle': 'Gestion immobilière complète pour maximiser vos rendements',
    'services.fullMgmt.title': 'Gestion Complète',
    'services.fullMgmt.desc': 'Communication avec les clients, ménage, tarification dynamique et maintenance — tout géré en toute fluidité.',
    'services.marketing.title': 'Marketing & Réservation',
    'services.marketing.desc': 'Création d\'annonces professionnelles, visibilité multi-plateformes et tarification dynamique.',
    'services.reporting.title': 'Rapports Propriétaire',
    'services.reporting.desc': 'Tableaux de bord mensuels avec revenus, taux d\'occupation et détails de maintenance.',
    'how.title': 'Comment ça marche',
    'how.subtitle': 'De l\'intégration à la gestion continue, nous simplifions tout',
    'how.step1.title': 'Semaine de Préparation',
    'how.step1.desc': 'Installation de poignées connectées, nettoyage et audit des équipements.',
    'how.step2.title': 'Mise en Ligne',
    'how.step2.desc': 'Shooting photo professionnel, annonces optimisées et lancement sur toutes les plateformes majeures.',
    'how.step3.title': 'Gestion Continue',
    'how.step3.desc': 'DOMOSIA gère tout — réservations, communication, ménage, maintenance et supervision opérationnelle complète.',
    'how.digitalNote': 'La gestion Digital-Only est disponible pour les propriétaires qui préfèrent gérer les opérations sur place mais souhaitent un support professionnel pour les annonces, la tarification et les réservations.',
    'how.learnMore': 'En savoir plus',
    'offers.title': 'Nos Offres',
    'offers.subtitle': 'Choisissez le plan adapté à vos besoins',
    'offers.full.title': 'Gestion Complète',
    'offers.full.badge': 'Service Premium',
    'offers.full.desc': 'Gestion immobilière clé en main. Tarification dynamique, communication clients, ménage, maintenance et tableaux de bord.',
    'offers.full.f1': 'Gestion complète des clients',
    'offers.full.f2': 'Coordination du ménage professionnel',
    'offers.full.f3': 'Optimisation tarifaire dynamique',
    'offers.full.f4': 'Maintenance & inspections',
    'offers.full.f5': 'Tableau de bord en temps réel',
    'offers.full.cta': 'Réserver une Consultation',
    'offers.digital.title': 'Digital-Only',
    'offers.digital.badge': 'Support Optionnel',
    'offers.digital.desc': 'Optimisation des annonces, tarification IA et support de réservation pour les propriétaires gérant les opérations sur site.',
    'offers.digital.f1': 'Annonces multi-plateformes',
    'offers.digital.f2': 'Tarification dynamique',
    'offers.digital.f3': 'Gestion des réservations',
    'offers.digital.f4': 'Analyses de performance',
    'offers.digital.cta': 'En savoir plus',
    'tech.title': 'Technologie Intelligente',
    'tech.subtitle': 'Alimentée par l\'innovation pour une efficacité maximale',
    'tech.smartAccess.title': 'Accès Intelligent',
    'tech.smartAccess.desc': 'Enregistrement et départ sans clé pour une expérience fluide.',
    'tech.automation.title': 'Système d\'Automatisation',
    'tech.automation.desc': 'Gestion centralisée des réservations, du ménage et des clients.',
    'tech.dashboard.title': 'Tableau de Bord',
    'tech.dashboard.desc': 'Revenus, taux d\'occupation et avis en temps réel.',
    'tech.pricing.title': 'Tarification Dynamique',
    'tech.pricing.desc': 'Optimisation IA pour un revenu maximal.',
    'tech.payments.title': 'Paiements Sécurisés',
    'tech.payments.desc': 'Transactions sûres et transparentes.',
    'tech.platforms.title': 'Plateformes Intégrées',
    'tech.platforms.desc': 'Synchronisation Airbnb, Booking.com, et plus.',
    'cta.title': 'Prêt à Maximiser le Potentiel de Votre Bien ?',
    'cta.subtitle': 'Laissez DOMOSIA transformer votre propriété en source de revenus passifs.',
    'cta.audit': 'Demander une Simulation de Revenus Gratuite',
    'cta.consultation': 'Planifier une Consultation',
    'footer.tagline': 'Votre bien, notre expertise.',
    'footer.quickLinks': 'Liens Rapides',
    'footer.contact': 'Contact',
    'footer.followUs': 'Suivez-nous',
    'footer.rights': '© 2026 DOMOSIA. Tous droits réservés.',
    'float.whatsapp': 'Discuter sur WhatsApp',
    'float.email': 'Envoyer un Email',

    // Simulator Translations
    "common.next": "Suivant",
    "common.back": "Retour",
    "common.mad": "MAD",
    "common.madPerYear": "MAD/an",
    "common.madPerNight": "MAD/nuit",
    "common.madPerMonth": "MAD/mois",
    "steps.contact": "Contact",
    "steps.property": "Propriété",
    "steps.location": "Localisation",
    "steps.amenities": "Équipements",
    "contact.intro": "Veuillez renseigner vos coordonnées pour recevoir votre simulation personnalisée.",
    "contact.fullName": "Nom complet",
    "contact.fullNamePlaceholder": "Ex: Ahmed Benali",
    "contact.fullNameError": "Veuillez entrer votre nom complet (min. 3 caractères)",
    "contact.email": "Email",
    "contact.emailPlaceholder": "Ex: ahmed@email.com",
    "contact.emailError": "Veuillez entrer une adresse email valide",
    "contact.phone": "Téléphone",
    "contact.phonePlaceholder": "Ex: +212 6 12 34 56 78",
    "contact.phoneError": "Numéro marocain valide requis (ex: +212612345678 ou 0612345678)",
    "property.type": "Type de propriété",
    "property.studio": "Studio",
    "property.apartment": "Appartement",
    "property.villa": "Villa",
    "property.riad": "Riad",
    "property.bedrooms": "Chambres",
    "property.beds": "Lits",
    "property.bathrooms": "Salles de bain",
    "property.toilets": "Toilettes",
    "location.city": "Ville",
    "location.cityPlaceholder": "Sélectionnez une ville",
    "location.neighborhood": "Quartier",
    "location.neighborhoodPlaceholder": "Sélectionnez un quartier",
    "location.longTermRent": "Loyer longue durée",
    "location.longTermRentHint": "Utilisé pour comparer avec les revenus locatifs courte durée",
    "location.outOfRange": "Données hors limites",
    "location.fixValues": "Veuillez corriger les valeurs avant de continuer.",
    "amenities.quality": "Qualité de l'ameublement",
    "amenities.basic": "Basique",
    "amenities.standard": "Standard",
    "amenities.luxury": "Luxe",
    "amenities.label": "Équipements",
    "amenities.wifi": "WiFi",
    "amenities.ac": "Climatisation",
    "amenities.pool": "Piscine",
    "amenities.parking": "Parking",
    "amenities.terrace": "Terrasse",
    "amenities.kitchen": "Cuisine équipée",
    "amenities.washer": "Machine à laver",
    "amenities.tv": "TV",
    "amenities.garden": "Jardin",
    "amenities.seaView": "Vue mer",
    "amenities.fireplace": "Cheminée",
    "amenities.jacuzzi": "Jacuzzi",
    "amenities.gym": "Salle de sport",
    "city.marrakech": "Marrakech",
    "city.casablanca": "Casablanca",
    "city.tangier": "Tanger",
    "city.agadir": "Agadir",
    "city.fes": "Fès",
    "city.essaouira": "Essaouira",
    "city.rabat": "Rabat",
    "city.chefchaouen": "Chefchaouen",
    "neighborhood.Médina": "Médina",
    "neighborhood.Guéliz": "Guéliz",
    "neighborhood.Hivernage": "Hivernage",
    "neighborhood.Palmeraie": "Palmeraie",
    "neighborhood.Targa": "Targa",
    "neighborhood.Route de l'Ourika": "Route de l'Ourika",
    "neighborhood.Maarif": "Maarif",
    "neighborhood.Anfa": "Anfa",
    "neighborhood.Gauthier": "Gauthier",
    "neighborhood.Bourgogne": "Bourgogne",
    "neighborhood.Ain Diab": "Ain Diab",
    "neighborhood.Centre Ville": "Centre Ville",
    "neighborhood.Kasbah": "Kasbah",
    "neighborhood.Ville Nouvelle": "Ville Nouvelle",
    "neighborhood.Malabata": "Malabata",
    "neighborhood.Tanja Marina": "Tanja Marina",
    "neighborhood.Cap Spartel": "Cap Spartel",
    "neighborhood.Boukhalef": "Boukhalef",
    "neighborhood.Bord de Mer": "Bord de Mer",
    "neighborhood.Founty": "Founty",
    "neighborhood.Sonaba": "Sonaba",
    "neighborhood.Charaf": "Charaf",
    "neighborhood.Talborjt": "Talborjt",
    "neighborhood.Bay d'Agadir": "Bay d'Agadir",
    "neighborhood.Fès el-Bali": "Fès el-Bali",
    "neighborhood.Fès el-Jdid": "Fès el-Jdid",
    "neighborhood.Route de Sefrou": "Route de Sefrou",
    "neighborhood.Ain Chkef": "Ain Chkef",
    "neighborhood.Diabat": "Diabat",
    "neighborhood.Quartier des Dunes": "Quartier des Dunes",
    "neighborhood.Agdal": "Agdal",
    "neighborhood.Hassan": "Hassan",
    "neighborhood.Les Orangers": "Les Orangers",
    "neighborhood.Hay Riad": "Hay Riad",
    "neighborhood.Souissi": "Souissi",
    "neighborhood.Ras el-Maa": "Ras el-Maa",
    "neighborhood.Quartier Andalou": "Quartier Andalou",
    "month.1": "Jan",
    "month.2": "Fév",
    "month.3": "Mar",
    "month.4": "Avr",
    "month.5": "Mai",
    "month.6": "Juin",
    "month.7": "Juil",
    "month.8": "Août",
    "month.9": "Sep",
    "month.10": "Oct",
    "month.11": "Nov",
    "month.12": "Déc",
    "val.maxBedrooms": "Maximum {count} chambres pour un {type}",
    "val.maxBeds": "Maximum {count} lits pour un {type}",
    "val.maxBathrooms": "Maximum {count} salles de bain pour un {type}",
    "val.rentRange": "Loyer attendu entre {min} et {max} MAD pour {city}",
    "val.rateCap": "Le tarif estimé dépasse le plafond réaliste de {cap} MAD/nuit pour ce type de bien dans cette ville",
    "val.unrealisticRevenue": "L'augmentation de revenu semble irréaliste. Veuillez vérifier vos données.",
    "form.simulate": "Simuler le revenu",
    "results.annualRevenue": "MAD/an",
    "results.simulationFor": "Simulation pour",
    "results.vsLongTerm": "vs longue durée",
    "results.highSeason": "Tarif haute saison",
    "results.lowSeason": "Tarif basse saison",
    "results.occupancy": "Taux d'occupation",
    "results.highLow": "haute / basse",
    "results.longTermRevenue": "Revenu longue durée",
    "results.monthlyEstimated": "Revenus mensuels estimés",
    "results.formula": "Formule : Revenu = tarif/nuit × taux d'occupation × 30 jours, avec pondération saisonnière",
    "results.scenario": "Scénario",
    "results.monthly": "Mensuel",
    "results.annual": "Annuel",
    "results.highSeasonLabel": "Haute saison",
    "results.lowSeasonLabel": "Basse saison",
    "results.annualEstimate": "Estimation annuelle",
    "results.monthlyComparison": "Comparaison mensuelle",
    "results.shortTerm": "Courte durée",
    "results.longTerm": "Longue durée",
    "results.bestCase": "Meilleur scénario",
    "results.bestCaseDesc": "Occupation optimale + haute demande",
    "results.worstCase": "Pire scénario",
    "results.worstCaseDesc": "Occupation faible + basse saison prolongée",
    "results.assumptions": "Hypothèses de la simulation",
    "results.newSimulation": "Nouvelle simulation",
    "results.downloadPdf": "Télécharger PDF",
    "results.generating": "Génération...",
    "results.unrealisticWarning": "Attention : résultats potentiellement irréalistes",
    "results.adjustRecommendation": "Nous vous recommandons de relancer la simulation avec des données ajustées.",
    "disclaimer": "⚠️ Avertissement : Les résultats estimés ne sont pas garantis et peuvent varier en fonction des conditions locales, de la saisonnalité, de la concurrence et de la qualité de gestion. Cette simulation est fournie à titre indicatif uniquement et ne constitue pas un engagement contractuel de la part de DOMOSIA.",
    "hero.badge": "Simulateur de revenus locatifs",
    "hero.title": "Estimez le potentiel de votre bien au Maroc",
    "hero.subtitle": "Comparez les revenus courte durée vs longue durée grâce aux données du marché marocain.",
    "hero.footer": "Les estimations sont basées sur les moyennes du marché marocain et ne constituent pas un conseil financier.",
    "assumptions.occupancy": "Taux d'occupation:",
    "assumptions.highSeason": "en haute saison,",
    "assumptions.lowSeason": "en basse saison",
    "assumptions.seasonInfo": "Haute saison Maroc : été, printemps, décembre, janvier + vacances scolaires (varie selon la ville)",
    "assumptions.formulaDetail": "Formule : Revenu = tarif/nuit × taux d'occupation × 30 jours",
    "assumptions.marketBased": "Tarifs basés sur les moyennes du marché marocain pour des propriétés similaires",
    "assumptions.feesNotIncluded": "Les frais de gestion, nettoyage et commissions plateforme ne sont pas inclus",
    "assumptions.scenarios": "Meilleur scénario: +15% sur l'estimation de base. Pire scénario: -30%",
  },
  ar: {
    'nav.services': 'الخدمات',
    'nav.howItWorks': 'كيف يعمل',
    'nav.offers': 'العروض',
    'nav.technology': 'التكنولوجيا',
    'nav.contact': 'اتصل بنا',
    'nav.faq': 'الأسئلة الشائعة',
    'nav.simulator': 'المحاكي',
    'hero.headline': 'دوموسيا، عقارك، خبرتنا.',
    'hero.subtext': 'حوّل عقارك إلى دخل ثابت وسهل مع إدارة احترافية و ذكية.',
    'hero.cta1': 'ابدأ الآن',
    'hero.cta2': 'اعرف المزيد',
    'services.title': 'خدماتنا',
    'services.subtitle': 'إدارة عقارية شاملة مصممة لتعظيم عوائدك',
    'services.fullMgmt.title': 'إدارة شاملة',
    'services.fullMgmt.desc': 'التواصل مع الضيوف، التنظيف، التسعير الديناميكي والصيانة — كل شيء يُدار بسلاسة.',
    'services.marketing.title': 'التسويق والحجز',
    'services.marketing.desc': 'إعداد إعلانات احترافية، ظهور على منصات متعددة، وتسعير ديناميكي.',
    'services.reporting.title': 'تقارير المالك',
    'services.reporting.desc': 'لوحات معلومات شهرية مع الدخل، معدلات الإشغال وتفاصيل الصيانة.',
    'how.title': 'كيف يعمل',
    'how.subtitle': 'من الإعداد إلى الإدارة المستمرة، نجعل كل شيء سلساً',
    'how.step1.title': 'أسبوع التحضير',
    'how.step1.desc': 'تركيب مقابض أبواب ذكية، تنظيف، ومراجعة المعدات.',
    'how.step2.title': 'الإطلاق',
    'how.step2.desc': 'تصوير احترافي، إعلانات محسّنة، وإطلاق على جميع المنصات الرئيسية.',
    'how.step3.title': 'إدارة مستمرة',
    'how.step3.desc': 'دوموسيا تتولى كل شيء — الحجوزات، التواصل مع الضيوف، التنظيف، الصيانة والإشراف التشغيلي الكامل.',
    'how.digitalNote': 'الإدارة الرقمية فقط متاحة للملاك الذين يفضلون التعامل مع العمليات الميدانية بأنفسهم لكنهم يريدون دعمًا احترافيًا في الإعلانات والتسعير والحجوزات.',
    'how.learnMore': 'اعرف المزيد',
    'offers.title': 'عروضنا',
    'offers.subtitle': 'اختر الخطة المناسبة لاحتياجاتك',
    'offers.full.title': 'إدارة شاملة',
    'offers.full.badge': 'خدمة مميزة',
    'offers.full.desc': 'إدارة عقارية كاملة دون عناء. تسعير ديناميكي، تواصل مع الضيوف، تنظيف، صيانة ولوحات معلومات حية.',
    'offers.full.f1': 'إدارة شاملة للضيوف',
    'offers.full.f2': 'تنسيق التنظيف الاحترافي',
    'offers.full.f3': 'تحسين التسعير الديناميكي',
    'offers.full.f4': 'الصيانة والتفتيش',
    'offers.full.f5': 'لوحة معلومات في الوقت الحقيقي',
    'offers.full.cta': 'احجز استشارة',
    'offers.digital.title': 'رقمي فقط',
    'offers.digital.badge': 'دعم اختياري',
    'offers.digital.desc': 'تحسين الإعلانات، تسعير بالذكاء الاصطناعي ودعم الحجوزات للملاك الذين يديرون العمليات الميدانية.',
    'offers.digital.f1': 'إعلانات متعددة المنصات',
    'offers.digital.f2': 'تسعير ديناميكي بالذكاء الاصطناعي',
    'offers.digital.f3': 'إدارة الحجوزات',
    'offers.digital.f4': 'تحليلات الأداء',
    'offers.digital.cta': 'اعرف المزيد',
    'tech.title': 'تكنولوجيا ذكية',
    'tech.subtitle': 'مدعومة بالابتكار لأقصى كفاءة',
    'tech.smartAccess.title': 'وصول ذكي',
    'tech.smartAccess.desc': 'تسجيل دخول وخروج بدون مفتاح لتجربة سلسة.',
    'tech.automation.title': 'نظام الأتمتة',
    'tech.automation.desc': 'إدارة مركزية للحجوزات والتنظيف والضيوف.',
    'tech.dashboard.title': 'لوحة المالك',
    'tech.dashboard.desc': 'الإيرادات والإشغال والتقييمات في لمحة.',
    'tech.pricing.title': 'تسعير ديناميكي',
    'tech.pricing.desc': 'تحسين بالذكاء الاصطناعي لأقصى إيرادات.',
    'tech.payments.title': 'مدفوعات آمنة',
    'tech.payments.desc': 'معاملات آمنة وشفافة.',
    'tech.platforms.title': 'منصات متكاملة',
    'tech.platforms.desc': 'مزامنة مع Airbnb وBooking.com والمزيد.',
    'cta.title': 'مستعد لتعظيم إمكانات عقارك؟',
    'cta.subtitle': 'دع دوموسيا تحوّل عقارك إلى مصدر دخل مميز.',
    'cta.audit': 'اطلب محاكاة إيرادات مجانية',
    'cta.consultation': 'جدولة استشارة',
    'footer.tagline': 'عقارك، خبرتنا.',
    'footer.quickLinks': 'روابط سريعة',
    'footer.contact': 'اتصل بنا',
    'footer.followUs': 'تابعنا',
    'footer.rights': '© 2026 دوموسيا. جميع الحقوق محفوظة.',
    'float.whatsapp': 'تحدث عبر واتساب',
    'float.email': 'أرسل بريداً',

    // Simulator Translations
    "common.next": "التالي",
    "common.back": "رجوع",
    "common.mad": "درهم",
    "common.madPerYear": "درهم/سنة",
    "common.madPerNight": "درهم/ليلة",
    "common.madPerMonth": "درهم/شهر",
    "steps.contact": "التواصل",
    "steps.property": "العقار",
    "steps.location": "الموقع",
    "steps.amenities": "المرافق",
    "contact.intro": "يرجى إدخال بياناتك للحصول على محاكاة مخصصة.",
    "contact.fullName": "الاسم الكامل",
    "contact.fullNamePlaceholder": "مثال: أحمد بنعلي",
    "contact.fullNameError": "يرجى إدخال اسمك الكامل (3 أحرف على الأقل)",
    "contact.email": "البريد الإلكتروني",
    "contact.emailPlaceholder": "مثال: ahmed@email.com",
    "contact.emailError": "يرجى إدخال بريد إلكتروني صالح",
    "contact.phone": "الهاتف",
    "contact.phonePlaceholder": "+212 6 12 34 56 78 :مثال",
    "contact.phoneError": "مطلوب رقم مغربي صالح (مثال: 0612345678 أو 212612345678+)",
    "property.type": "نوع العقار",
    "property.studio": "استوديو",
    "property.apartment": "شقة",
    "property.villa": "فيلا",
    "property.riad": "رياض",
    "property.bedrooms": "غرف النوم",
    "property.beds": "الأسرّة",
    "property.bathrooms": "الحمامات",
    "property.toilets": "المراحيض",
    "location.city": "المدينة",
    "location.cityPlaceholder": "اختر مدينة",
    "location.neighborhood": "الحي",
    "location.neighborhoodPlaceholder": "اختر حياً",
    "location.longTermRent": "إيجار طويل الأمد",
    "location.longTermRentHint": "يُستخدم للمقارنة مع إيرادات الإيجار القصير الأمد",
    "location.outOfRange": "بيانات خارج النطاق",
    "location.fixValues": "يرجى تصحيح القيم قبل المتابعة.",
    "amenities.quality": "جودة الأثاث",
    "amenities.basic": "أساسي",
    "amenities.standard": "عادي",
    "amenities.luxury": "فاخر",
    "amenities.label": "المرافق",
    "amenities.wifi": "واي فاي",
    "amenities.ac": "تكييف",
    "amenities.pool": "مسبح",
    "amenities.parking": "موقف سيارات",
    "amenities.terrace": "تراس",
    "amenities.kitchen": "مطبخ مجهز",
    "amenities.washer": "غسالة",
    "amenities.tv": "تلفاز",
    "amenities.garden": "حديقة",
    "amenities.seaView": "إطلالة بحرية",
    "amenities.fireplace": "مدفأة",
    "amenities.jacuzzi": "جاكوزي",
    "amenities.gym": "صالة رياضة",
    "city.marrakech": "مراكش",
    "city.casablanca": "الدار البيضاء",
    "city.tangier": "طنجة",
    "city.agadir": "أكادير",
    "city.fes": "فاس",
    "city.essaouira": "الصويرة",
    "city.rabat": "الرباط",
    "city.chefchaouen": "شفشاون",
    "neighborhood.Médina": "المدينة القديمة",
    "neighborhood.Guéliz": "جيليز",
    "neighborhood.Hivernage": "هيفيرناج",
    "neighborhood.Palmeraie": "النخيل",
    "neighborhood.Targa": "تاركة",
    "neighborhood.Route de l'Ourika": "طريق أوريكا",
    "neighborhood.Maarif": "المعاريف",
    "neighborhood.Anfa": "أنفا",
    "neighborhood.Gauthier": "غوتييه",
    "neighborhood.Bourgogne": "بوركون",
    "neighborhood.Ain Diab": "عين دياب",
    "neighborhood.Centre Ville": "وسط المدينة",
    "neighborhood.Kasbah": "القصبة",
    "neighborhood.Ville Nouvelle": "المدينة الجديدة",
    "neighborhood.Malabata": "مالاباطا",
    "neighborhood.Tanja Marina": "طنجة مارينا",
    "neighborhood.Cap Spartel": "كاب سبارتيل",
    "neighborhood.Boukhalef": "بوخالف",
    "neighborhood.Bord de Mer": "شاطئ البحر",
    "neighborhood.Founty": "فونتي",
    "neighborhood.Sonaba": "سونابا",
    "neighborhood.Charaf": "شرف",
    "neighborhood.Talborjt": "تالبرجت",
    "neighborhood.Bay d'Agadir": "خليج أكادير",
    "neighborhood.Fès el-Bali": "فاس البالي",
    "neighborhood.Fès el-Jdid": "فاس الجديد",
    "neighborhood.Route de Sefrou": "طريق صفرو",
    "neighborhood.Ain Chkef": "عين الشقف",
    "neighborhood.Diabat": "ديابات",
    "neighborhood.Quartier des Dunes": "حي الكثبان",
    "neighborhood.Agdal": "أكدال",
    "neighborhood.Hassan": "حسان",
    "neighborhood.Les Orangers": "ليمون",
    "neighborhood.Hay Riad": "حي الرياض",
    "neighborhood.Souissi": "السويسي",
    "neighborhood.Ras el-Maa": "رأس الماء",
    "neighborhood.Quartier Andalou": "حي الأندلس",
    "month.1": "يناير",
    "month.2": "فبراير",
    "month.3": "مارس",
    "month.4": "أبريل",
    "month.5": "مايو",
    "month.6": "يونيو",
    "month.7": "يوليو",
    "month.8": "أغسطس",
    "month.9": "سبتمبر",
    "month.10": "أكتوبر",
    "month.11": "نوفمبر",
    "month.12": "ديسمبر",
    "val.maxBedrooms": "بحد أقصى {count} غرف نوم لـ {type}",
    "val.maxBeds": "بحد أقصى {count} أسرة لـ {type}",
    "val.maxBathrooms": "بحد أقصى {count} حمامات لـ {type}",
    "val.rentRange": "الإيجار المتوقع بين {min} و {max} درهم لـ {city}",
    "val.rateCap": "يتجاوز السعر المقدر السقف الواقعي البالغ {cap} درهم/ليلة لهذا النوع من العقارات في هذه المدينة",
    "val.unrealisticRevenue": "زيادة الإيرادات تبدو غير واقعية. يرجى التحقق من بياناتك.",
    "form.simulate": "محاكاة الإيرادات",
    "results.annualRevenue": "درهم/سنة",
    "results.simulationFor": "محاكاة لـ",
    "results.vsLongTerm": "مقارنة بالإيجار الطويل",
    "results.highSeason": "سعر الموسم المرتفع",
    "results.lowSeason": "سعر الموسم المنخفض",
    "results.occupancy": "نسبة الإشغال",
    "results.highLow": "مرتفع / منخفض",
    "results.longTermRevenue": "إيرادات طويلة الأمد",
    "results.monthlyEstimated": "الإيرادات الشهرية المقدرة",
    "results.formula": "الصيغة: الإيرادات = السعر/ليلة × نسبة الإشغال × 30 يوماً، مع ترجيح موسمي",
    "results.scenario": "السيناريو",
    "results.monthly": "شهري",
    "results.annual": "سنوي",
    "results.highSeasonLabel": "الموسم المرتفع",
    "results.lowSeasonLabel": "الموسم المنخفض",
    "results.annualEstimate": "التقدير السنوي",
    "results.monthlyComparison": "مقارنة شهرية",
    "results.shortTerm": "قصير الأمد",
    "results.longTerm": "طويل الأمد",
    "results.bestCase": "أفضل سيناريو",
    "results.bestCaseDesc": "إشغال مثالي + طلب مرتفع",
    "results.worstCase": "أسوأ سيناريو",
    "results.worstCaseDesc": "إشغال ضعيف + موسم منخفض ممتد",
    "results.assumptions": "فرضيات المحاكاة",
    "results.newSimulation": "محاكاة جديدة",
    "results.downloadPdf": "تحميل PDF",
    "results.generating": "جاري التوليد...",
    "results.unrealisticWarning": "تنبيه: نتائج قد تكون غير واقعية",
    "results.adjustRecommendation": "نوصي بإعادة المحاكاة ببيانات معدلة.",
    "disclaimer": "⚠️ تنبيه: النتائج المقدّرة غير مضمونة وقد تتغير حسب الظروف المحلية والموسمية والمنافسة وجودة الإدارة. هذه المحاكاة مقدمة لأغراض إعلامية فقط ولا تشكل التزاماً تعاقدياً من طرف DOMOSIA.",
    "hero.badge": "محاكي إيرادات الإيجار",
    "hero.title": "قدّر إمكانيات عقارك في المغرب",
    "hero.subtitle": "قارن إيرادات الإيجار القصير والطويل الأمد باستخدام بيانات السوق المغربي.",
    "hero.footer": "التقديرات مبنية على متوسطات السوق المغربي ولا تعتبر استشارة مالية.",
    "assumptions.occupancy": "نسبة الإشغال:",
    "assumptions.highSeason": "في الموسم المرتفع،",
    "assumptions.lowSeason": "في الموسم المنخفض",
    "assumptions.seasonInfo": "الموسم المرتفع في المغرب: الصيف، الربيع، ديسمبر، يناير + العطل المدرسية (يختلف حسب المدينة)",
    "assumptions.formulaDetail": "الصيغة: الإيرادات = السعر/ليلة × نسبة الإشغال × 30 يوماً",
    "assumptions.marketBased": "الأسعار مبنية على متوسطات السوق المغربي لعقارات مماثلة",
    "assumptions.feesNotIncluded": "رسوم الإدارة والتنظيف وعمولات المنصة غير مشمولة",
    "assumptions.scenarios": "أفضل سيناريو: 15%+ على التقدير الأساسي. أسوأ سيناريو: 30%-",
  },
};

// Amenity translation mapping (original French label → i18n key)
export const AMENITY_KEYS: Record<string, string> = {
  "WiFi": "amenities.wifi",
  "Climatisation": "amenities.ac",
  "Piscine": "amenities.pool",
  "Parking": "amenities.parking",
  "Terrasse": "amenities.terrace",
  "Cuisine équipée": "amenities.kitchen",
  "Machine à laver": "amenities.washer",
  "TV": "amenities.tv",
  "Jardin": "amenities.garden",
  "Vue mer": "amenities.seaView",
  "Cheminée": "amenities.fireplace",
  "Jacuzzi": "amenities.jacuzzi",
  "Salle de sport": "amenities.gym",
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [lang, setLangState] = useState<Language>(() => {
    // Check URL param first (e.g. ?lang=en), then localStorage
    const urlLang = new URLSearchParams(window.location.search).get("lang");
    if (urlLang === 'en' || urlLang === 'fr' || urlLang === 'ar') {
      return urlLang as Language;
    }
    const savedLang = localStorage.getItem('app_language');
    if (savedLang === 'en' || savedLang === 'fr' || savedLang === 'ar') {
      return savedLang as Language;
    }
    return 'en';
  });

  const setLang = (newLang: Language) => {
    setLangState(newLang);
    localStorage.setItem('app_language', newLang);
  };

  const t = (key: string, params?: Record<string, any>): string => {
    let text = translations[lang][key] || key;
    if (params) {
      Object.entries(params).forEach(([k, v]) => {
        // If the value looks like a translation key (starts with city. or property.), translate it too
        const val = (typeof v === "string" && (v.startsWith("city.") || v.startsWith("property.") || v.startsWith("neighborhood."))) ? t(v) : v;
        text = text.replace(`{${k}}`, String(val));
      });
    }
    return text;
  };

  const dir = lang === 'ar' ? 'rtl' : 'ltr';

  useEffect(() => {
    document.documentElement.dir = dir;
    document.documentElement.lang = lang;
  }, [dir, lang]);

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, dir }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
};
